#! /usr/bin/env python2.7
# -*- coding: utf-8 -*-

import sys, os

if len(sys.argv) > 1:
	os.system("git status")

	commit = ' '.join(sys.argv[1:])

	try:
		msg = raw_input("\n{}Commit as '{}'? (S/N) {}".format("\033[92m", commit,"\033[0m"))
	except KeyboardInterrupt:
		print "\033[93m\n\nAborted!\n\033[0m"
		sys.exit(0)

	if msg == 'S' or msg == 's': 
		os.system("git add -A")
		os.system("git commit -am " + commit)
		os.system("git push -u origin master")
	else:
		print "\033[93m\nAborted!\n\033[0m"
else:
	print "\033[93m\nUsage:\ngitit My commit message\n\033[0m"
